In [3]:
import pandas as pd

In [4]:
scores = pd.read_csv('./data/spreadspoke_scores.csv')

In [5]:
scores.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
0,09/02/1966,1966,1,False,Miami Dolphins,14,23,Oakland Raiders,NaN,NaN,NaN,Orange Bowl,False,83.0,6.0,71,NaN
1,09/03/1966,1966,1,False,Houston Oilers,45,7,Denver Broncos,NaN,NaN,NaN,Rice Stadium,False,81.0,7.0,70,NaN
2,09/04/1966,1966,1,False,San Diego Chargers,27,7,Buffalo Bills,NaN,NaN,NaN,Balboa Stadium,False,70.0,7.0,82,NaN
3,09/09/1966,1966,2,False,Miami Dolphins,14,19,New York Jets,NaN,NaN,NaN,Orange Bowl,False,82.0,11.0,78,NaN
4,09/10/1966,1966,1,False,Green Bay Packers,24,3,Baltimore Colts,NaN,NaN,NaN,Lambeau Field,False,64.0,8.0,62,NaN

In [25]:
scores05 = pd.DataFrame(scores[scores['schedule_season']>= 2005])

In [26]:
scores05.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
8673,09/08/2005,2005,1,False,New England Patriots,30,20,Oakland Raiders,NE,-7.5,50,Gillette Stadium,False,71.0,9.0,64,NaN
8674,09/11/2005,2005,1,False,Baltimore Ravens,7,24,Indianapolis Colts,IND,-3.0,47,M&T Bank Stadium,False,69.0,4.0,63,NaN
8675,09/11/2005,2005,1,False,Buffalo Bills,22,7,Houston Texans,BUF,-4.5,39,Ralph Wilson Stadium,False,64.0,8.0,58,NaN
8676,09/11/2005,2005,1,False,Carolina Panthers,20,23,New Orleans Saints,CAR,-6.5,45.5,Bank of America Stadium,False,74.0,12.0,49,NaN
8677,09/11/2005,2005,1,False,Cleveland Browns,13,27,Cincinnati Bengals,CIN,-3.5,44.5,FirstEnergy Stadium,False,69.0,6.0,63,NaN

In [34]:
scores05[scores05['schedule_season'] == 2019].head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
12411,2019-09-05,2019,1,False,Chicago Bears,3,10,Green Bay Packers,CHI,-3.0,46.5,Soldier Field,False,NaN,NaN,NaN,NaN
12412,2019-09-08,2019,1,False,Arizona Cardinals,27,27,Detroit Lions,DET,-3.0,45.5,University of Phoenix Stadium,False,72.0,0.0,NaN,DOME
12413,2019-09-08,2019,1,False,Carolina Panthers,27,30,Los Angeles Rams,LAR,-2.0,49.5,Bank of America Stadium,False,NaN,NaN,NaN,NaN
12414,2019-09-08,2019,1,False,Cleveland Browns,13,43,Tennessee Titans,CLE,-5.5,44,FirstEnergy Stadium,False,NaN,NaN,NaN,NaN
12415,2019-09-08,2019,1,False,Dallas Cowboys,35,17,New York Giants,DAL,-7.0,44,AT&T Stadium,False,72.0,0.0,NaN,DOME

In [28]:
scores05['schedule_date'] = pd.to_datetime(scores05['schedule_date'])

In [33]:
scores05[scores05['schedule_date'] == '2020-02-02']

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
12677,2020-02-02,2019,Superbowl,True,Kansas City Chiefs,31,20,San Francisco 49ers,KC,-1.5,53,Hard Rock Stadium,True,NaN,NaN,NaN,NaN

In [30]:
scores05.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4005 entries, 8673 to 12677
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   schedule_date        4005 non-null   datetime64[ns]
 1   schedule_season      4005 non-null   int64
 2   schedule_week        4005 non-null   object
 3   schedule_playoff     4005 non-null   bool
 4   team_home            4005 non-null   object
 5   score_home           4005 non-null   int64
 6   score_away           4005 non-null   int64
 7   team_away            4005 non-null   object
 8   team_favorite_id     4005 non-null   object
 9   spread_favorite      4005 non-null   float64
 10  over_under_line      4005 non-null   object
 11  stadium              4005 non-null   object
 12  stadium_neutral      4005 non-null   bool
 13  weather_temperature  3721 non-null   float64
 14  weather_wind_mph     3721 non-null   float64
 15  weather_humidity     1632 non-null   object
 16  weather_detail       1183 non-null   object
dtypes: bool(2), datetime64[ns](1), float64(3), int64(3), object(8)
memory usage: 508.4+ KB

### will decide on weather later

In [12]:
scores05.shape

(4005, 17)